id: A4BBB97DC
base_file: f9D4D.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:41:04.014122
  last_modified_at: 2022-05-31 06:41:04.014129
