id: A4BBB97DC
base_file: fE96B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:41:04.016510
  last_modified_at: 2022-05-31 06:41:04.016515
